local ui = loadstring(game:HttpGet("https://raw.githubusercontent.com/soapware/UI/main/WallyHub/main.lua"))()

-- UI:Init(parent)
-- Init:AddTab(title)
-- AddTab:AddSection(title)
-- AddSection:AddButton(text, callback)
-- AddSection:AddSlider(text, default, callback)
-- AddSection:AddKeybind(text, default, callback)
-- AddSection:AddToggle(text, default, callback)

local mainUI = ui:Init(game:GetService("CoreGui"))
local homeTab = mainUI:AddTab("Home")
local autoTab = mainUI:AddTab("Auto")
local farmSection = homeTab:AddSection("Auto Farmers")
local farmMobs = farmSection:AddToggle("Auto Farm Mobs", false, function(value)
print(value)
end)
local farmBosses = farmSection:AddToggle("Auto Farm Bosses", false, function(value)
print(value)
end)
local killAll = farmSection:AddButton("Kill All", function()
print("Kill All")
end)
local tpSpeed = farmSection:AddSlider("TP Speed", {min = 16, max = 64, def = 40}, function(value)
print(value)
end)
local homeSettings = homeTab:AddSection("Settings")
local rainbowColour = homeSettings:AddToggle("Toggle Rainbow", false, function(value)
print(value)
end)
local espToggle = homeSettings:AddToggle("Toggle ESP", false, function(value)
print(value)
end)

local keybindSection = autoTab:AddSection("Keybinds")
local autoBuy = keybindSection:AddKeybind("Auto Buy Weapons", Enum.KeyCode.Q, function(value)
print(value)
end)
local autoSell = keybindSection:AddKeybind("Auto Sell Weapons", Enum.KeyCode.R, function(value)
print(value)
end)
local miscSection = autoTab:AddSection("Miscellaneous")
local autoRejoinInterval = miscSection:AddSlider("Rejoin Interval", {min = 500, max = 1200, def = 700}, function(value)
print(value)
end)
local manualRejoin = miscSection:AddButton("Rejoin", function()
print("Rejoin")
end)
